[workspace]

members = [ 
    "octasine",
    "octasine_vst",
    "simd_sleef_sin35",
]

[profile.release]
debug = true
lto = true
opt-level = 3

[profile.test]
# lto = true
opt-level = 3

[profile.bench]
lto = true
opt-level = 3