[workspace]
resolver = "2"

members = [ 
    "bench_process",
    "octasine",
    "octasine_vst2_plugin",
    "plot_curves",
    "run_gui",
]

# [patch.'https://github.com/RustAudio/baseview']
# baseview = { path = "../baseview" }

# [patch.'https://github.com/BillyDM/iced_baseview']
# iced_baseview = { path = "../iced_baseview" }

# [patch.'https://github.com/iced-rs/iced_audio']
# iced_audio = { path = "../iced_audio" }

[patch.crates-io.glow_glyph]
git = "https://github.com/greatest-ape/glow_glyph.git"
rev = "3b65f54" # branch: explicit_attrib_location

[patch.'https://github.com/iced-rs/iced_audio'.iced_audio]
git = "https://github.com/greatest-ape/iced_audio.git"
rev = "709eee0" # branch: bipolar-knob-noncenter

[profile.release]
debug = false
lto = "thin"
opt-level = 3

[profile.test]
opt-level = 3

[profile.bench]
inherits = "release"

[profile.release-debug]
inherits = "release"
debug = true
