[package]
name = "fm"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
edition = "2018"

[lib]
name = "fm"
crate-type = ["cdylib"]

[dependencies]
array-init = "0.0.4"
dirs = "1"
log = "0.3"
log-panics = "2"
parking_lot = "0.7"
rand = "0.6"
simplelog = "0.4"
smallvec = "0.6"
vst = { git = "https://github.com/rust-dsp/rust-vst.git" }

[profile.release]
debug = true
