[workspace]

members = [ 
    "octasine",
    "octasine_vst",
    # "simd_sleef_sin35",
]

# Use sleef-sys fork
# [patch.crates-io.sleef-sys]
# git = 'https://github.com/greatest-ape/sleef-sys.git'
# branch = "octasine"
# features = ["static"]

[profile.release]
debug = true
lto = true
opt-level = 3

[profile.test]
# lto = true
opt-level = 3

[profile.bench]
debug = true
lto = true
opt-level = 3