[workspace]
resolver = "2"

members = [ 
    "bench_process",
    "octasine",
    "octasine_vst2_plugin",
    "plot_curves",
    "run_gui",
]


# [patch.'https://github.com/RustAudio/baseview']
# baseview = { path = "../baseview" }

# [patch.'https://github.com/BillyDM/iced_baseview']
# iced_baseview = { path = "../iced_baseview" }

# [patch.'https://github.com/iced-rs/iced_audio']
# iced_audio = { path = "../iced_audio" }

[profile.release]
debug = false
lto = true
opt-level = 3

[profile.test]
opt-level = 3

[profile.bench]
debug = false
lto = true
opt-level = 3

[profile.release-debug]
inherits = "release"
debug = true