[package]
name = "plot_envelopes"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
plotlib = "0.4"

[dependencies.vst2_helpers]
path = "../vst2_helpers"

[dependencies.octasine]
path = "../octasine"