[package]
name = "octasine"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
license = "GPL-3.0"
edition = "2018"

[features]
default = []
simd = ["sleef-sys", "arrayvec"]
logging = ["dirs", "log", "log-panics", "simplelog"]

[lib]
name = "octasine"

[[bench]]
name = "process"
harness = false

[dependencies]
arrayvec = { version = "0.5", optional = true }
array-init = "0.1"
fastrand = "1"
itertools = "0.9"
vst = "0.2"

# Logging
dirs = { version = "3", optional = true}
log = { version = "0.4", optional = true, default-features = false }
log-panics = { version = "2", optional = true }
simplelog = { version = "0.8", optional = true, default-features = false }

[dependencies.vst2_helpers]
path = "../vst2_helpers"

[dependencies.sleef-sys]
git = 'https://github.com/greatest-ape/sleef-sys.git'
branch = "octasine"
features = ["static"]
optional = true

[dev-dependencies]
assert_approx_eq = "1"
quickcheck = { version = "0.9", default-features = false }