[package]
name = "octasine"
version = "0.8.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
license = "AGPL-3.0"
edition = "2021"

[features]
gui_glow = ["gui", "iced_baseview/glow", "iced_baseview/glow_canvas"]
gui_wgpu = ["gui", "iced_baseview/wgpu", "iced_baseview/wgpu_canvas"]
gui = ["baseview", "iced_baseview", "iced_audio", "palette", "raw-window-handle", "rfd", "tinyfiledialogs"]

[lib]
name = "octasine"

[dev-dependencies]
assert_approx_eq = "1"
quickcheck = { version = "1", default-features = false }

[dependencies]
anyhow = "1"
arc-swap = "1"
array-init = "2"
arrayvec = "0.7"
byteorder = "1"
cfg-if = "1"
directories = "4"
duplicate = "0.4"
fast-math = "0.1"
fastrand = "1"
flate2 = "1"
git-testament = "0.2"
log = { version = "0.4", default-features = false }
log-panics = "2"
once_cell = "1"
os_info = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = { version = "0.12", default-features = false, features = ["local-offset"] }
sleef-trig = { git = "https://github.com/greatest-ape/sleef-trig.git", rev = "4713dfd" }
vst = "0.3"

# GUI

iced_audio = { version = "0.8", optional = true }
palette = { version = "0.6", optional = true }
raw-window-handle = { version = "0.4", optional = true }
rfd = { version = "0.10", optional = true, default-features = false, features = ["xdg-portal"] }
tinyfiledialogs = { version = "3", optional = true }

[dependencies.baseview]
git = "https://github.com/rustaudio/baseview.git"
rev = "b3712638bacb3fdf2883cb5aa3f6caed0e91ac8c"
optional = true

[dependencies.iced_baseview]
git = "https://github.com/BillyDM/iced_baseview.git"
rev = "b78fa8057d1b7ba0adf0351a59173ec4e8ec9ee4" # branch: main
default-features = false
optional = true
