[package]
name = "octasine"
version = "0.5.2"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
license = "AGPL-3.0"
edition = "2018"

[features]
default = ["logging", "gui_glow"]
simd = ["sleef-sys"]
logging = ["dirs", "git-testament", "log", "log-panics", "os_info", "simplelog"]
gui_glow = ["gui", "iced_glow", "raw-gl-context", "iced_baseview/glow", "iced_baseview/glow_canvas"]
gui_wgpu = ["gui", "iced_wgpu", "iced_baseview/wgpu", "iced_baseview/canvas"]
gui = ["baseview", "iced_baseview", "iced_style", "iced_audio", "palette", "raw-window-handle", "git-testament"]

[lib]
name = "octasine"

[[bench]]
name = "process"
harness = false

[dependencies]
anyhow = "1"
arc-swap = "1"
arrayvec = "0.7"
array-init = "2"
cfg-if = "1"
duplicate = "0.3"
fastrand = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
vst = "0.2"

# Logging

dirs = { version = "3", optional = true}
log = { version = "0.4", optional = true, default-features = false }
log-panics = { version = "2", optional = true }
os_info = { version = "3", optional = true }
simplelog = { version = "0.10", optional = true, default-features = false }

# GUI

raw-window-handle = { version = "0.3", optional = true }
git-testament = { version = "0.2", optional = true }
raw-gl-context = { version = "0.1", optional = true }
iced_glow = { version = "0.2", optional = true }
iced_wgpu = { version = "0.4", optional = true }

[dependencies.baseview]
git = "https://github.com/rustaudio/baseview.git"
branch = "master"
optional = true

[dependencies.iced_baseview]
git = "https://github.com/BillyDM/iced_baseview.git"
rev = "b879d0fabb0a9b5bb122fae8c0db608c6025d472"
default-features = false
features = ["palette"]
optional = true

[dependencies.iced_style]
version = "0.3"
optional = true

[dependencies.iced_audio]
git = "https://github.com/BillyDM/iced_audio.git"
branch = "main"
optional = true

[dependencies.palette]
version = "0.5"
optional = true

# SIMD

# Fork with static linking and avx instruction generation
[dependencies.sleef-sys]
git = 'https://github.com/greatest-ape/sleef-sys.git'
branch = "octasine"
features = ["static"]
optional = true

[dev-dependencies]
assert_approx_eq = "1"
colored = "2"
quickcheck = { version = "1", default-features = false }
sha2 = "0.9"
