[package]
name = "octasine"
version = "0.6.1"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
license = "AGPL-3.0"
edition = "2021"

[features]
simd = ["sleef-sys"]
gui_glow = ["gui", "iced_glow", "iced_baseview/glow", "iced_baseview/glow_canvas"]
gui_wgpu = ["gui", "iced_wgpu", "iced_baseview/wgpu", "iced_baseview/wgpu_canvas"]
gui = ["baseview", "iced_baseview", "iced_style", "iced_audio", "palette", "raw-window-handle"]

[lib]
name = "octasine"

[dev-dependencies]
assert_approx_eq = "1"
quickcheck = { version = "1", default-features = false }

[dependencies]
anyhow = "1"
arc-swap = "1"
array-init = "2"
arrayvec = "0.7"
cfg-if = "1"
directories = "4"
duplicate = "0.4"
fastrand = "1"
flate2 = "1"
git-testament = "0.2"
log = { version = "0.4", default-features = false }
log-panics = "2"
once_cell = "1"
os_info = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = { version = "0.12", default-features = false, features = ["local-offset"] }
vst = { git = "https://github.com/RustAudio/vst-rs.git", rev = "b5f342c" }

# GUI

raw-window-handle = { version = "0.4", optional = true }

[dependencies.baseview]
git = "https://github.com/rustaudio/baseview.git"
rev = "b3712638bacb3fdf2883cb5aa3f6caed0e91ac8c"
optional = true

[dependencies.iced_baseview]
git = "https://github.com/BillyDM/iced_baseview.git"
rev = "9d1876147859a92753e82ddf2f225ceab3cf2648" # iced_git branch
default-features = false
features = ["palette"]
optional = true

[dependencies.iced_glow]
git = "https://github.com/iced-rs/iced.git"
rev = "a53fa91e0ddf374bbeb66d5e831b79127ed47a9d"
optional = true

[dependencies.iced_wgpu]
git = "https://github.com/iced-rs/iced.git"
rev = "a53fa91e0ddf374bbeb66d5e831b79127ed47a9d"
optional = true

[dependencies.iced_style]
git = "https://github.com/iced-rs/iced.git"
rev = "a53fa91e0ddf374bbeb66d5e831b79127ed47a9d"
optional = true

[dependencies.iced_audio]
git = "https://github.com/iced-rs/iced_audio.git"
rev = "5b67e157275a73ce2043bdfda154709bf378f112" # iced_git branch
optional = true

[dependencies.palette]
version = "0.5"
optional = true

# SIMD

# sleef-sys fork with static linking and avx instruction generation
[dependencies.sleef-sys]
git = 'https://github.com/greatest-ape/sleef-sys.git'
rev = "9625d96e64bc83ec18202e206c5fe1e5423df35b" # octasine branch
features = ["static"]
optional = true
