[package]
name = "octasine"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
license = "GPL-3.0"
edition = "2018"

[features]
default = []
simd = ["packed_simd", "simd_sleef_sin35"]
logging = ["dirs", "log", "log-panics", "simplelog"]

[lib]
name = "octasine"

[[bin]]
name = "plot-envelopes"

[[bench]]
name = "sample-gen"
harness = false

[[bench]]
name = "process"
harness = false

[[bench]]
name = "sin"
harness = false

[dependencies]
array-init = "0.0.4"
parking_lot = "0.7"
plotlib = "0.4"
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = "0.6"

# Logging
dirs = { version = "1", optional = true}
log = { version = "0.3", optional = true }
log-panics = { version = "2", optional = true }
simplelog = { version = "0.4", optional = true }

[dependencies.vst]
git = "https://github.com/RustAudio/vst-rs.git"
rev = "269adb"

[dependencies.vst2_helpers]
path = "../vst2_helpers"

[dependencies.packed_simd]
git = "https://github.com/rust-lang-nursery/packed_simd.git"
rev = "173f55"
optional = true
features = ["sleef-sys"]

[dependencies.simd_sleef_sin35]
path = "../simd_sleef_sin35"
optional = true
features = ["simd"]

[dev-dependencies]
assert_approx_eq = "1"
quickcheck = "0.8"
quickcheck_macros = "0.8"
statistical = "1"
