[package]
name = "octasine"
version = "0.6.1"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
license = "AGPL-3.0"
edition = "2021"

[features]
simd = ["sleef-sys"]
gui_glow = ["gui", "iced_baseview/glow", "iced_baseview/glow_canvas"]
gui_wgpu = ["gui", "iced_baseview/wgpu", "iced_baseview/wgpu_canvas"]
gui = ["baseview", "iced_baseview", "iced_audio", "palette", "raw-window-handle"]

[lib]
name = "octasine"

[dev-dependencies]
assert_approx_eq = "1"
quickcheck = { version = "1", default-features = false }

[dependencies]
anyhow = "1"
arc-swap = "1"
array-init = "2"
arrayvec = "0.7"
cfg-if = "1"
directories = "4"
duplicate = "0.4"
fastrand = "1"
flate2 = "1"
git-testament = "0.2"
log = { version = "0.4", default-features = false }
log-panics = "2"
once_cell = "1"
os_info = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = { version = "0.12", default-features = false, features = ["local-offset"] }
vst = { git = "https://github.com/RustAudio/vst-rs.git", rev = "b5f342c" }

# GUI

raw-window-handle = { version = "0.4", optional = true }

[dependencies.baseview]
git = "https://github.com/rustaudio/baseview.git"
rev = "b3712638bacb3fdf2883cb5aa3f6caed0e91ac8c"
optional = true

[dependencies.iced_baseview]
git = "https://github.com/BillyDM/iced_baseview.git"
rev = "b78fa8057d1b7ba0adf0351a59173ec4e8ec9ee4" # branch: main
default-features = false
optional = true

[dependencies.iced_audio]
git = "https://github.com/iced-rs/iced_audio.git"
rev = "b54a87477386815a9f70664edf540f9a4e72fd69" # branch: main
optional = true

[dependencies.palette]
version = "0.5"
optional = true

# SIMD

# sleef-sys fork with static linking and avx instruction generation
[dependencies.sleef-sys]
git = 'https://github.com/greatest-ape/sleef-sys.git'
rev = "9625d96e64bc83ec18202e206c5fe1e5423df35b" # branch: octasine
features = ["static"]
optional = true
