[package]
name = "octasine"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
license = "GPL-3.0"
edition = "2018"

[features]
default = []
# simd = ["packed_simd", "simd_sleef_sin35"]
simd2 = ["simdeez", "arrayvec"]
logging = ["dirs", "log", "log-panics", "simplelog"]

[lib]
name = "octasine"

[[bin]]
name = "plot-envelopes"

[[bench]]
name = "sample-gen"
harness = false

[[bench]]
name = "process"
harness = false

[[bench]]
name = "sin"
harness = false

[dependencies]
arrayvec = { version = "0.5", optional = true }
array-init = "0.1"
cfg-if = "0.1"
parking_lot = "0.10"
plotlib = "0.4"
rand = { version = "0.7", features = ["small_rng"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = "1"
vst = "0.2"

# Logging
dirs = { version = "2", optional = true}
log = { version = "0.4", optional = true }
log-panics = { version = "2", optional = true }
simplelog = { version = "0.7", optional = true }

[dependencies.vst2_helpers]
path = "../vst2_helpers"

# [dependencies.packed_simd]
# git = "https://github.com/rust-lang-nursery/packed_simd.git"
# optional = true
# features = ["sleef-sys"]

# [dependencies.simd_sleef_sin35]
# path = "../simd_sleef_sin35"
# optional = true
# features = ["simd"]

[dependencies.simdeez]
git = 'https://github.com/greatest-ape/simdeez.git'
branch = "octasine"
features = ["sleef"]
optional = true

[dev-dependencies]
assert_approx_eq = "1"
quickcheck = "0.9"
quickcheck_macros = "0.9"
statistical = "1"
