[package]
name = "vst2_helpers"
version = "0.1.0"
authors = ["Joakim Frostegård <joakim.frostegard@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "vst2_helpers"

[dependencies]
array-init = "0.0.4"
assert_approx_eq = "1"
parking_lot = "0.7"
plotlib = "0.4"
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = "0.6"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
statistical = "1"