name: Releases

on: 
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install baseview dependencies
      run: |
        sudo apt update
        sudo apt install libx11-xcb-dev libxcb-dri2-0-dev libgl1-mesa-dev libxcb-icccm4-dev libxcursor-dev
      if: contains(matrix.os, 'ubuntu')

    # Required for bindgen on Windows, see https://github.com/rust-lang/rust-bindgen/issues/1797
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      if: contains(matrix.os, 'windows')
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      if: contains(matrix.os, 'windows')

    - name: Install latest nightly Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: clippy

    - name: Install cargo-deny
      run: cargo install --locked cargo-deny

    - name: Check licenses of dependencies
      run: cargo deny --workspace --all-features check licenses

    - name: Build plugin in release mode
      run: cargo +nightly build --release --features "simd" -p octasine_vst2_plugin --verbose

    - name: Create release directory
      run: mkdir releases

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Create release file (macOS)
      run: |
        bash ./scripts/macos/bundle.sh "./target/release/liboctasine.dylib"
        bash ./scripts/unix/package.sh "OctaSine.vst" "../releases/OctaSine-${{ steps.get_version.outputs.VERSION }}-macOS-Intel"
      if: contains(matrix.os, 'macos')
  
    - name: Create release file (Windows)
      run: |
        New-Item "tmp\OctaSine" -ItemType Directory -ea 0
        Copy-Item "LICENSE" -Destination "tmp\OctaSine\LICENSE.txt"
        Copy-Item "target\release\octasine.dll" -Destination "tmp\OctaSine\OctaSine.dll"
        Compress-Archive -Path "tmp\OctaSine" -DestinationPath releases\OctaSine-${{ steps.get_version.outputs.VERSION }}-Windows.zip -CompressionLevel Optimal
      if: contains(matrix.os, 'windows')

    - name: Create release file (Linux)
      run: |
        mkdir -p tmp
        cp "./target/release/liboctasine.so" "tmp/OctaSine.so"
        bash ./scripts/unix/package.sh "OctaSine.so" "../releases/OctaSine-${{ steps.get_version.outputs.VERSION }}-Ubuntu-20_04"
      if: contains(matrix.os, 'ubuntu')

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "releases/*.zip"
        draft: true
        allowUpdates: true
        artifactErrorsFailBuild: true
        token: ${{ secrets.GITHUB_TOKEN }}
