name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo +nightly build --release --all-features --verbose
    - name: Run tests
      run: cargo +nightly test --workspace --exclude plot_envelopes --all-features --release --verbose
